/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prueba48;

import java.awt.Graphics;
import java.awt.image.ImageObserver;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author admin
 */
public class main_menu extends javax.swing.JFrame {

    /**
     * Creates new form main_menu
     */
    public main_menu() {
        initComponents();
        ImageIcon icon = new ImageIcon(getClass().getResource("/icons/main_icon.png"));
        setIconImage(icon.getImage());
        
        // Configurar el fondo personalizado
        setContentPane(new JPanel() {
            ImageIcon backgroundImage = new ImageIcon(getClass().getResource("/images/backgroupmenu.jpg"));
            
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(backgroundImage.getImage(), 0, 0, getWidth(), getHeight(), (ImageObserver) this);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        sub_menu_agg_user = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menu_proovedores = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menu_inventario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        setName("main_menu"); // NOI18N
        setState(1);
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });

        jMenuBar1.setBackground(new java.awt.Color(60, 63, 65));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        jMenu1.setForeground(new java.awt.Color(0, 0, 0));
        jMenu1.setText("RRHH");

        sub_menu_agg_user.setText("agregar usuario");
        sub_menu_agg_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_menu_agg_userActionPerformed(evt);
            }
        });
        jMenu1.add(sub_menu_agg_user);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("COMPRAS");
        jMenu2.add(jSeparator1);

        menu_proovedores.setText(" Provedores");
        menu_proovedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_proovedoresActionPerformed(evt);
            }
        });
        jMenu2.add(menu_proovedores);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("PRODUCTOS");

        menu_inventario.setText("INVETARIO");
        menu_inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_inventarioActionPerformed(evt);
            }
        });
        jMenu3.add(menu_inventario);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1032, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sub_menu_agg_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_menu_agg_userActionPerformed
        // TODO add your handling code here:
        agg_new_user agg_user_win = new agg_new_user();
        agg_user_win.setVisible(true);
        
    }//GEN-LAST:event_sub_menu_agg_userActionPerformed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowStateChanged

    private void menu_proovedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_proovedoresActionPerformed
        // TODO add your handling code here:
        proveedor menu_proveedor = new proveedor();
        menu_proveedor.setVisible(true);
    }//GEN-LAST:event_menu_proovedoresActionPerformed

    private void menu_inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_inventarioActionPerformed
        // TODO add your handling code here:
        inventario_prod menu_productos = new inventario_prod();
        menu_productos.setVisible(true);
        
        
    }//GEN-LAST:event_menu_inventarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem menu_inventario;
    private javax.swing.JMenuItem menu_proovedores;
    private javax.swing.JMenuItem sub_menu_agg_user;
    // End of variables declaration//GEN-END:variables
}
